// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP1qaf9eTvuoc0Ck78laDzq-h_Gzi-T64',
    appId: '1:840575688524:web:3d5b70679fc164fc2e39e9',
    messagingSenderId: '840575688524',
    projectId: 'travellapp-34d57',
    authDomain: 'travellapp-34d57.firebaseapp.com',
    storageBucket: 'travellapp-34d57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIaf680zQQHnKJuza4wQy6LK7vQ8wD0QY',
    appId: '1:840575688524:android:4f4cbc93f394ba092e39e9',
    messagingSenderId: '840575688524',
    projectId: 'travellapp-34d57',
    storageBucket: 'travellapp-34d57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiKMeSoExhMTKYjpPS2Dz47lemOSYMPPA',
    appId: '1:840575688524:ios:ebf2cc9e0207ecac2e39e9',
    messagingSenderId: '840575688524',
    projectId: 'travellapp-34d57',
    storageBucket: 'travellapp-34d57.firebasestorage.app',
    iosBundleId: 'com.example.travellapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiKMeSoExhMTKYjpPS2Dz47lemOSYMPPA',
    appId: '1:840575688524:ios:ebf2cc9e0207ecac2e39e9',
    messagingSenderId: '840575688524',
    projectId: 'travellapp-34d57',
    storageBucket: 'travellapp-34d57.firebasestorage.app',
    iosBundleId: 'com.example.travellapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP1qaf9eTvuoc0Ck78laDzq-h_Gzi-T64',
    appId: '1:840575688524:web:1dceeb26f32e14372e39e9',
    messagingSenderId: '840575688524',
    projectId: 'travellapp-34d57',
    authDomain: 'travellapp-34d57.firebaseapp.com',
    storageBucket: 'travellapp-34d57.firebasestorage.app',
  );
}
